### ISSUE TITLE
Cannot destructure property `exts`

### ISSUE THREAD

**Issue by TomS-** [fansenze/parcel-plugin-url-loader#10]
uikit.less:undefined:undefined: Cannot destructure property `exts` of 'undefined' or 'null'. 

This is the error I'm getting while using this with UIKit, UIKit by default uses Webpack and some of the SVG's is links too need to be inlined. I want to purge the result and decided to go for Parcel. Currently this error is the only thing preventing me doing that.

**Comment by fansenze** [comment]
> uikit.less:undefined:undefined: Cannot destructure property `exts` of 'undefined' or 'null'.
> 
> This is the error I'm getting while using this with UIKit, UIKit by default uses Webpack and some of the SVG's is links too need to be inlined. I want to purge the result and decided to go for Parcel. Currently this error is the only thing preventing me doing that.

give me your parcel & url-loader version and more error stack
