### ISSUE TITLE
Doesn't work with @import and has promise error

### ISSUE THREAD

**Issue by TomS-** [fansenze/parcel-plugin-url-loader#11]
```
(node:5044) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at handlerAssets.forEach (C:\Users\user\Documents\Projects\site\templates\node_modules\parcel-plugin-url-loader\lib\index.js:23:14)
```

This is the promise error I'm receiving. Also it is not trying to inline any of the less files I import.

**Comment by fansenze** [comment]
> ```
> (node:5044) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
>     at assertPath (path.js:39:11)
>     at Object.resolve (path.js:166:7)
>     at handlerAssets.forEach (C:\Users\user\Documents\Projects\site\templates\node_modules\parcel-plugin-url-loader\lib\index.js:23:14)
> ```
> 
> This is the promise error I'm receiving. Also it is not trying to inline any of the less files I import.

give me your parce & url-loader version
