### ISSUE TITLE
[Bug]Cannot read property 'generated' of undefined

### ISSUE THREAD

**Issue by sKawashima** [fansenze/parcel-plugin-url-loader#3]
🚨  Cannot read property 'generated' of undefined
    at Packager.addAsset (/Users/*******/node_modules/parcel-plugin-url-loader/lib/packager.js:34:46)

**Comment by fansenze** [comment]
tell me:
node verison
parcel-bundler verison

**Comment by sKawashima** [comment]
sorry:
node version: v8.9.3
parcel-bundler verison: 1.6.2

**Comment by mweibel** [comment]
Same here, custom config of parcelrc:
```json
{
  "url-loader": {
    "exts": ["obj"],
    "limit": 10240
  }
}
```

Error happens because of line 20: 
```js
let mod = asset.depAssets.get(dep.name)
```

`asset.depAssets` is an empty map at this point. 
`dep.name` seems to be `package.json` in my particular case.

**Comment by fansenze** [comment]
sorry, i am to busy with working, so i forget to fix it
i fix it in parcel-plugin-url-loader's version >= **1.2.3**
