### ISSUE TITLE
cannot support images in css???

### ISSUE THREAD

**Issue by Dellear** [fansenze/parcel-plugin-url-loader#5]

**Comment by lvisei** [comment]
## I encountered the same problem,but will influence images in css
![tim 20180606142625](https://user-images.githubusercontent.com/26923747/41020490-a50eff0e-6995-11e8-9cd4-ebc6a4ee22ba.jpg)

**Comment by fansenze** [comment]
`^1.2.5` fixed: #6 
now only can encode images in `.js`, because there is some problems with parcel
also i will try to do it

**Comment by perymimon** [comment]
what about that ?  I see in my code that image in css are still separated

**Comment by fansenze** [comment]
🎉`^1.3.0` support encode images(includes `svg`) in **css**
let's try it
