### ISSUE TITLE
favicon.png changes to js file

### ISSUE THREAD

**Issue by ol-web** [fansenze/parcel-plugin-url-loader#6]
In my index.html file I have this:
`<link rel="shortcut icon" href="favicon.png" />`

after being compiled with this plugin on, it turns to this:
`<link rel="shortcut icon" href="/favicon.d82d2c87.js">`

It just turns a png to a js file no matter if the file size. Can this be fixed? This plugin is part of my full stack parcel-based boilerplate.

**Comment by fansenze** [comment]
fixed in `1.2.5`

**Comment by ol-web** [comment]
~~ok, extensions work now but the favicon.png file is filled with undefined instead: https://i.imgur.com/9enTCkD.png~~

ok, without [parcel-plugin-imagemin](https://github.com/DeMoorJasper/parcel-plugin-imagemin) everything works good again. don't know why these two plugins don't work together. maybe because they both have ImageAsset classes?

**Comment by fansenze** [comment]
yeah, all of assets only can have a `AssetClass` and a `Packager` in `parcel`
