### ISSUE TITLE
Do not output the encoded files to the dist folder

### ISSUE THREAD

**Issue by jarvisniu** [fansenze/parcel-plugin-url-loader#8]
Output the encoded files to the dist folder is useless, redundant.
We may be confused: "Why they are still here? Does the plugin take effect?".
And also it will expend more space of the repo and server.
——Well done, 兄弟！

**Comment by fansenze** [comment]
🎉`^1.3.1` will unlink file in `production`(parcel env)

**Comment by jarvisniu** [comment]
Great!
