### ISSUE TITLE
collection is empty ,so unlink will not effect

### ISSUE THREAD

**Issue by Futami233** [fansenze/parcel-plugin-url-loader#9]
const handlerAssets = collection.get()
console.log(handlerAssets)
but log only get Map {},and it is empty.
So output the useless files to the dist folder.

**Comment by Futami233** [comment]
"parcel-bundler": "^1.12.3"
"parcel-plugin-url-loader": "^1.3.1"

**Comment by fansenze** [comment]
@Futami233 
it is only unlink **encoded** files while use `parcel build`
and i try to build with `parcel-bundler 1.12.3`, it will unlink the useless files

**Comment by Futami233** [comment]
in my project, files has been encoded, but handlerAssets is empty.
I used postcss-modules and sass, and is it the reason?

this.bundleNameMap.forEach(fileName=>{
      if (needUnlink(fileName))  outputs.push(`${outDir}/${fileName}`) 
})

I change the function with using bundleNameMap, and It's ok

**Comment by fansenze** [comment]
maybe these plugins register `Assets Type` in `parcel`, so make the `Assets Type` of `url-loader` invalid
